### ISSUE TITLE
How can I stop the animation?

### ISSUE THREAD

**Issue by dkpetkova** [joakimkemeny/jke.d3.ecg#1]
I have some question. I don't have much experience with java script. I am wondering can I stop the animation of the ECG graphic after some period of time?

**Comment by joakimkemeny** [comment]
The chart works by showing all data points added to it so to stop it you should stop feeding it data points.

In the example the data points are added using `setInterval` and to stop this you can use `clearInterval` like this:

``` javascript
// Generate a new data point based on the heart rate.
var intervalId = setInterval(function () {
    $('.jke-ecgChart').ecgChart('addDataPoint', getDataPoint());
}, interval);

// Stop the chart after 5 seconds.
setTimeout(function () {
    clearTimeout(intervalId);
}, 5000);
```
